# Generated by Django 5.1.7 on 2025-04-21 19:18

import django.db.models.deletion
import django_countries.fields
import miembros.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255, validators=[miembros.models.validar_nombre], verbose_name='Nombre Completo')),
                ('pais', django_countries.fields.CountryField(max_length=2, verbose_name='País de Residencia')),
                ('numero_telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Número de Teléfono')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('activo', models.BooleanField(default=True)),
                ('puede_regresar', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(default='Publicidad no autorizada', max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad_llamados', models.PositiveIntegerField(default=1)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanciones', to='miembros.miembro')),
            ],
        ),
    ]
