# Generated by Django 5.1.7 on 2025-04-21 21:34

import django.db.models.deletion
import django_countries.fields
import miembros.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='nombre_completo',
            field=models.CharField(max_length=255, validators=[miembros.models.validar_nombre]),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='numero_telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='pais',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.CreateModel(
            name='SolicitudCorreccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('atendido', models.BooleanField(default=False)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='miembros.miembro')),
            ],
        ),
    ]
